// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/ember/v1/cache.proto

package emberv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{3}
}

type DelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRequest) Reset() {
	*x = DelRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRequest) ProtoMessage() {}

func (x *DelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRequest.ProtoReflect.Descriptor instead.
func (*DelRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelResponse) Reset() {
	*x = DelResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelResponse) ProtoMessage() {}

func (x *DelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelResponse.ProtoReflect.Descriptor instead.
func (*DelResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DelResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsRequest) Reset() {
	*x = ExistsRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsRequest) ProtoMessage() {}

func (x *ExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsRequest.ProtoReflect.Descriptor instead.
func (*ExistsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{6}
}

func (x *ExistsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{7}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{8}
}

func (x *TypeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeResponse) Reset() {
	*x = TypeResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeResponse) ProtoMessage() {}

func (x *TypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeResponse.ProtoReflect.Descriptor instead.
func (*TypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{9}
}

func (x *TypeResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ExpireRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireRequest) Reset() {
	*x = ExpireRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireRequest) ProtoMessage() {}

func (x *ExpireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireRequest.ProtoReflect.Descriptor instead.
func (*ExpireRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{10}
}

func (x *ExpireRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ExpireRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type ExpireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpireResponse) Reset() {
	*x = ExpireResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpireResponse) ProtoMessage() {}

func (x *ExpireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpireResponse.ProtoReflect.Descriptor instead.
func (*ExpireResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{11}
}

func (x *ExpireResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type TtlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtlRequest) Reset() {
	*x = TtlRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtlRequest) ProtoMessage() {}

func (x *TtlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtlRequest.ProtoReflect.Descriptor instead.
func (*TtlRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{12}
}

func (x *TtlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type TtlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	HasExpiration bool                   `protobuf:"varint,2,opt,name=has_expiration,json=hasExpiration,proto3" json:"has_expiration,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TtlResponse) Reset() {
	*x = TtlResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TtlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TtlResponse) ProtoMessage() {}

func (x *TtlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TtlResponse.ProtoReflect.Descriptor instead.
func (*TtlResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{13}
}

func (x *TtlResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *TtlResponse) GetHasExpiration() bool {
	if x != nil {
		return x.HasExpiration
	}
	return false
}

func (x *TtlResponse) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type HSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSetRequest) Reset() {
	*x = HSetRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetRequest) ProtoMessage() {}

func (x *HSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetRequest.ProtoReflect.Descriptor instead.
func (*HSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{14}
}

func (x *HSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HSetRequest) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int64                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HSetResponse) Reset() {
	*x = HSetResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HSetResponse) ProtoMessage() {}

func (x *HSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HSetResponse.ProtoReflect.Descriptor instead.
func (*HSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{15}
}

func (x *HSetResponse) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

type HGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetRequest) Reset() {
	*x = HGetRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetRequest) ProtoMessage() {}

func (x *HGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetRequest.ProtoReflect.Descriptor instead.
func (*HGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{16}
}

func (x *HGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HGetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type HGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetResponse) Reset() {
	*x = HGetResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetResponse) ProtoMessage() {}

func (x *HGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetResponse.ProtoReflect.Descriptor instead.
func (*HGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{17}
}

func (x *HGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *HGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HDelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Fields        []string               `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HDelRequest) Reset() {
	*x = HDelRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HDelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelRequest) ProtoMessage() {}

func (x *HDelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelRequest.ProtoReflect.Descriptor instead.
func (*HDelRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{18}
}

func (x *HDelRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HDelRequest) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type HDelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int64                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HDelResponse) Reset() {
	*x = HDelResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HDelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HDelResponse) ProtoMessage() {}

func (x *HDelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HDelResponse.ProtoReflect.Descriptor instead.
func (*HDelResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{19}
}

func (x *HDelResponse) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type HGetAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetAllRequest) Reset() {
	*x = HGetAllRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllRequest) ProtoMessage() {}

func (x *HGetAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllRequest.ProtoReflect.Descriptor instead.
func (*HGetAllRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{20}
}

func (x *HGetAllRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type HGetAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HGetAllResponse) Reset() {
	*x = HGetAllResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HGetAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HGetAllResponse) ProtoMessage() {}

func (x *HGetAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HGetAllResponse.ProtoReflect.Descriptor instead.
func (*HGetAllResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{21}
}

func (x *HGetAllResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *HGetAllResponse) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type LPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPushRequest) Reset() {
	*x = LPushRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushRequest) ProtoMessage() {}

func (x *LPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushRequest.ProtoReflect.Descriptor instead.
func (*LPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{22}
}

func (x *LPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LPushRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type LPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPushResponse) Reset() {
	*x = LPushResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPushResponse) ProtoMessage() {}

func (x *LPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPushResponse.ProtoReflect.Descriptor instead.
func (*LPushResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{23}
}

func (x *LPushResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type RPushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPushRequest) Reset() {
	*x = RPushRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushRequest) ProtoMessage() {}

func (x *RPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushRequest.ProtoReflect.Descriptor instead.
func (*RPushRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{24}
}

func (x *RPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RPushRequest) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type RPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Length        int64                  `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPushResponse) Reset() {
	*x = RPushResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPushResponse) ProtoMessage() {}

func (x *RPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPushResponse.ProtoReflect.Descriptor instead.
func (*RPushResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{25}
}

func (x *RPushResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type LPopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPopRequest) Reset() {
	*x = LPopRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopRequest) ProtoMessage() {}

func (x *LPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopRequest.ProtoReflect.Descriptor instead.
func (*LPopRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{26}
}

func (x *LPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type LPopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LPopResponse) Reset() {
	*x = LPopResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LPopResponse) ProtoMessage() {}

func (x *LPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LPopResponse.ProtoReflect.Descriptor instead.
func (*LPopResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{27}
}

func (x *LPopResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RPopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPopRequest) Reset() {
	*x = RPopRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopRequest) ProtoMessage() {}

func (x *RPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopRequest.ProtoReflect.Descriptor instead.
func (*RPopRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{28}
}

func (x *RPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type RPopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RPopResponse) Reset() {
	*x = RPopResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPopResponse) ProtoMessage() {}

func (x *RPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPopResponse.ProtoReflect.Descriptor instead.
func (*RPopResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{29}
}

func (x *RPopResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *RPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type LRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	Stop          int64                  `protobuf:"varint,3,opt,name=stop,proto3" json:"stop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeRequest) Reset() {
	*x = LRangeRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeRequest) ProtoMessage() {}

func (x *LRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeRequest.ProtoReflect.Descriptor instead.
func (*LRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{30}
}

func (x *LRangeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LRangeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *LRangeRequest) GetStop() int64 {
	if x != nil {
		return x.Stop
	}
	return 0
}

type LRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LRangeResponse) Reset() {
	*x = LRangeResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LRangeResponse) ProtoMessage() {}

func (x *LRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LRangeResponse.ProtoReflect.Descriptor instead.
func (*LRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{31}
}

func (x *LRangeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LRangeResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAddRequest) Reset() {
	*x = SAddRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddRequest) ProtoMessage() {}

func (x *SAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddRequest.ProtoReflect.Descriptor instead.
func (*SAddRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{32}
}

func (x *SAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SAddRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Added         int64                  `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAddResponse) Reset() {
	*x = SAddResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAddResponse) ProtoMessage() {}

func (x *SAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAddResponse.ProtoReflect.Descriptor instead.
func (*SAddResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{33}
}

func (x *SAddResponse) GetAdded() int64 {
	if x != nil {
		return x.Added
	}
	return 0
}

type SRemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRemRequest) Reset() {
	*x = SRemRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemRequest) ProtoMessage() {}

func (x *SRemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemRequest.ProtoReflect.Descriptor instead.
func (*SRemRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{34}
}

func (x *SRemRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SRemRequest) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SRemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Removed       int64                  `protobuf:"varint,1,opt,name=removed,proto3" json:"removed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SRemResponse) Reset() {
	*x = SRemResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SRemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SRemResponse) ProtoMessage() {}

func (x *SRemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SRemResponse.ProtoReflect.Descriptor instead.
func (*SRemResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{35}
}

func (x *SRemResponse) GetRemoved() int64 {
	if x != nil {
		return x.Removed
	}
	return 0
}

type SMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMembersRequest) Reset() {
	*x = SMembersRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersRequest) ProtoMessage() {}

func (x *SMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersRequest.ProtoReflect.Descriptor instead.
func (*SMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{36}
}

func (x *SMembersRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Members       []string               `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMembersResponse) Reset() {
	*x = SMembersResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMembersResponse) ProtoMessage() {}

func (x *SMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMembersResponse.ProtoReflect.Descriptor instead.
func (*SMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{37}
}

func (x *SMembersResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *SMembersResponse) GetMembers() []string {
	if x != nil {
		return x.Members
	}
	return nil
}

type SIsMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Member        string                 `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIsMemberRequest) Reset() {
	*x = SIsMemberRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIsMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberRequest) ProtoMessage() {}

func (x *SIsMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberRequest.ProtoReflect.Descriptor instead.
func (*SIsMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{38}
}

func (x *SIsMemberRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SIsMemberRequest) GetMember() string {
	if x != nil {
		return x.Member
	}
	return ""
}

type SIsMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMember      bool                   `protobuf:"varint,1,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SIsMemberResponse) Reset() {
	*x = SIsMemberResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SIsMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SIsMemberResponse) ProtoMessage() {}

func (x *SIsMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SIsMemberResponse.ProtoReflect.Descriptor instead.
func (*SIsMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{39}
}

func (x *SIsMemberResponse) GetIsMember() bool {
	if x != nil {
		return x.IsMember
	}
	return false
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{40}
}

func (x *PublishRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     int64                  `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{41}
}

func (x *PublishResponse) GetDelivered() int64 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channels      []string               `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{42}
}

func (x *SubscribeRequest) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

type SubscribeMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Channel         string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	Payload         []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	PublishedAtUnix int64                  `protobuf:"varint,3,opt,name=published_at_unix,json=publishedAtUnix,proto3" json:"published_at_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeMessage) Reset() {
	*x = SubscribeMessage{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessage) ProtoMessage() {}

func (x *SubscribeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessage.ProtoReflect.Descriptor instead.
func (*SubscribeMessage) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{43}
}

func (x *SubscribeMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *SubscribeMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SubscribeMessage) GetPublishedAtUnix() int64 {
	if x != nil {
		return x.PublishedAtUnix
	}
	return 0
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{44}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalKeys     int64                  `protobuf:"varint,1,opt,name=total_keys,json=totalKeys,proto3" json:"total_keys,omitempty"`
	StringKeys    int64                  `protobuf:"varint,2,opt,name=string_keys,json=stringKeys,proto3" json:"string_keys,omitempty"`
	HashKeys      int64                  `protobuf:"varint,3,opt,name=hash_keys,json=hashKeys,proto3" json:"hash_keys,omitempty"`
	ListKeys      int64                  `protobuf:"varint,4,opt,name=list_keys,json=listKeys,proto3" json:"list_keys,omitempty"`
	SetKeys       int64                  `protobuf:"varint,5,opt,name=set_keys,json=setKeys,proto3" json:"set_keys,omitempty"`
	Channels      int64                  `protobuf:"varint,6,opt,name=channels,proto3" json:"channels,omitempty"`
	Subscribers   int64                  `protobuf:"varint,7,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{45}
}

func (x *StatsResponse) GetTotalKeys() int64 {
	if x != nil {
		return x.TotalKeys
	}
	return 0
}

func (x *StatsResponse) GetStringKeys() int64 {
	if x != nil {
		return x.StringKeys
	}
	return 0
}

func (x *StatsResponse) GetHashKeys() int64 {
	if x != nil {
		return x.HashKeys
	}
	return 0
}

func (x *StatsResponse) GetListKeys() int64 {
	if x != nil {
		return x.ListKeys
	}
	return 0
}

func (x *StatsResponse) GetSetKeys() int64 {
	if x != nil {
		return x.SetKeys
	}
	return 0
}

func (x *StatsResponse) GetChannels() int64 {
	if x != nil {
		return x.Channels
	}
	return 0
}

func (x *StatsResponse) GetSubscribers() int64 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{46}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_ember_v1_cache_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_cache_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_cache_proto_rawDescGZIP(), []int{47}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_ember_v1_cache_proto protoreflect.FileDescriptor

const file_proto_ember_v1_cache_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/ember/v1/cache.proto\x12\bember.v1\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"U\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\r\n" +
	"\vSetResponse\"\x1e\n" +
	"\n" +
	"DelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"'\n" +
	"\vDelResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"!\n" +
	"\rExistsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x1f\n" +
	"\vTypeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\"\n" +
	"\fTypeResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"B\n" +
	"\rExpireRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"*\n" +
	"\x0eExpireResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\"\x1e\n" +
	"\n" +
	"TtlRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"k\n" +
	"\vTtlResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12%\n" +
	"\x0ehas_expiration\x18\x02 \x01(\bR\rhasExpiration\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\x95\x01\n" +
	"\vHSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x06fields\x18\x02 \x03(\v2!.ember.v1.HSetRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\fHSetResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x03R\x05added\"5\n" +
	"\vHGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\":\n" +
	"\fHGetResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"7\n" +
	"\vHDelRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06fields\x18\x02 \x03(\tR\x06fields\"(\n" +
	"\fHDelResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x03R\aremoved\"\"\n" +
	"\x0eHGetAllRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xa1\x01\n" +
	"\x0fHGetAllResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12=\n" +
	"\x06fields\x18\x02 \x03(\v2%.ember.v1.HGetAllResponse.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fLPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"'\n" +
	"\rLPushResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\"8\n" +
	"\fRPushRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"'\n" +
	"\rRPushResponse\x12\x16\n" +
	"\x06length\x18\x01 \x01(\x03R\x06length\"\x1f\n" +
	"\vLPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\fLPopResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1f\n" +
	"\vRPopRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\fRPopResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"K\n" +
	"\rLRangeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x12\n" +
	"\x04stop\x18\x03 \x01(\x03R\x04stop\">\n" +
	"\x0eLRangeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"9\n" +
	"\vSAddRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"$\n" +
	"\fSAddResponse\x12\x14\n" +
	"\x05added\x18\x01 \x01(\x03R\x05added\"9\n" +
	"\vSRemRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"(\n" +
	"\fSRemResponse\x12\x18\n" +
	"\aremoved\x18\x01 \x01(\x03R\aremoved\"#\n" +
	"\x0fSMembersRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"B\n" +
	"\x10SMembersResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x18\n" +
	"\amembers\x18\x02 \x03(\tR\amembers\"<\n" +
	"\x10SIsMemberRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06member\x18\x02 \x01(\tR\x06member\"0\n" +
	"\x11SIsMemberResponse\x12\x1b\n" +
	"\tis_member\x18\x01 \x01(\bR\bisMember\"D\n" +
	"\x0ePublishRequest\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"/\n" +
	"\x0fPublishResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\x03R\tdelivered\".\n" +
	"\x10SubscribeRequest\x12\x1a\n" +
	"\bchannels\x18\x01 \x03(\tR\bchannels\"r\n" +
	"\x10SubscribeMessage\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12*\n" +
	"\x11published_at_unix\x18\x03 \x01(\x03R\x0fpublishedAtUnix\"\x0e\n" +
	"\fStatsRequest\"\xe2\x01\n" +
	"\rStatsResponse\x12\x1d\n" +
	"\n" +
	"total_keys\x18\x01 \x01(\x03R\ttotalKeys\x12\x1f\n" +
	"\vstring_keys\x18\x02 \x01(\x03R\n" +
	"stringKeys\x12\x1b\n" +
	"\thash_keys\x18\x03 \x01(\x03R\bhashKeys\x12\x1b\n" +
	"\tlist_keys\x18\x04 \x01(\x03R\blistKeys\x12\x19\n" +
	"\bset_keys\x18\x05 \x01(\x03R\asetKeys\x12\x1a\n" +
	"\bchannels\x18\x06 \x01(\x03R\bchannels\x12 \n" +
	"\vsubscribers\x18\a \x01(\x03R\vsubscribers\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x88\v\n" +
	"\fCacheService\x122\n" +
	"\x03Get\x12\x14.ember.v1.GetRequest\x1a\x15.ember.v1.GetResponse\x122\n" +
	"\x03Set\x12\x14.ember.v1.SetRequest\x1a\x15.ember.v1.SetResponse\x122\n" +
	"\x03Del\x12\x14.ember.v1.DelRequest\x1a\x15.ember.v1.DelResponse\x12;\n" +
	"\x06Exists\x12\x17.ember.v1.ExistsRequest\x1a\x18.ember.v1.ExistsResponse\x125\n" +
	"\x04Type\x12\x15.ember.v1.TypeRequest\x1a\x16.ember.v1.TypeResponse\x12;\n" +
	"\x06Expire\x12\x17.ember.v1.ExpireRequest\x1a\x18.ember.v1.ExpireResponse\x122\n" +
	"\x03Ttl\x12\x14.ember.v1.TtlRequest\x1a\x15.ember.v1.TtlResponse\x125\n" +
	"\x04HSet\x12\x15.ember.v1.HSetRequest\x1a\x16.ember.v1.HSetResponse\x125\n" +
	"\x04HGet\x12\x15.ember.v1.HGetRequest\x1a\x16.ember.v1.HGetResponse\x125\n" +
	"\x04HDel\x12\x15.ember.v1.HDelRequest\x1a\x16.ember.v1.HDelResponse\x12>\n" +
	"\aHGetAll\x12\x18.ember.v1.HGetAllRequest\x1a\x19.ember.v1.HGetAllResponse\x128\n" +
	"\x05LPush\x12\x16.ember.v1.LPushRequest\x1a\x17.ember.v1.LPushResponse\x128\n" +
	"\x05RPush\x12\x16.ember.v1.RPushRequest\x1a\x17.ember.v1.RPushResponse\x125\n" +
	"\x04LPop\x12\x15.ember.v1.LPopRequest\x1a\x16.ember.v1.LPopResponse\x125\n" +
	"\x04RPop\x12\x15.ember.v1.RPopRequest\x1a\x16.ember.v1.RPopResponse\x12;\n" +
	"\x06LRange\x12\x17.ember.v1.LRangeRequest\x1a\x18.ember.v1.LRangeResponse\x125\n" +
	"\x04SAdd\x12\x15.ember.v1.SAddRequest\x1a\x16.ember.v1.SAddResponse\x125\n" +
	"\x04SRem\x12\x15.ember.v1.SRemRequest\x1a\x16.ember.v1.SRemResponse\x12A\n" +
	"\bSMembers\x12\x19.ember.v1.SMembersRequest\x1a\x1a.ember.v1.SMembersResponse\x12D\n" +
	"\tSIsMember\x12\x1a.ember.v1.SIsMemberRequest\x1a\x1b.ember.v1.SIsMemberResponse\x12>\n" +
	"\aPublish\x12\x18.ember.v1.PublishRequest\x1a\x19.ember.v1.PublishResponse\x12E\n" +
	"\tSubscribe\x12\x1a.ember.v1.SubscribeRequest\x1a\x1a.ember.v1.SubscribeMessage0\x01\x128\n" +
	"\x05Stats\x12\x16.ember.v1.StatsRequest\x1a\x17.ember.v1.StatsResponse\x12;\n" +
	"\x06Health\x12\x17.ember.v1.HealthRequest\x1a\x18.ember.v1.HealthResponseB>Z<github.com/EricNguyen1206/erionn-ember/proto/ember/v1;emberv1b\x06proto3"

var (
	file_proto_ember_v1_cache_proto_rawDescOnce sync.Once
	file_proto_ember_v1_cache_proto_rawDescData []byte
)

func file_proto_ember_v1_cache_proto_rawDescGZIP() []byte {
	file_proto_ember_v1_cache_proto_rawDescOnce.Do(func() {
		file_proto_ember_v1_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ember_v1_cache_proto_rawDesc), len(file_proto_ember_v1_cache_proto_rawDesc)))
	})
	return file_proto_ember_v1_cache_proto_rawDescData
}

var file_proto_ember_v1_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 50)
var file_proto_ember_v1_cache_proto_goTypes = []any{
	(*GetRequest)(nil),        // 0: ember.v1.GetRequest
	(*GetResponse)(nil),       // 1: ember.v1.GetResponse
	(*SetRequest)(nil),        // 2: ember.v1.SetRequest
	(*SetResponse)(nil),       // 3: ember.v1.SetResponse
	(*DelRequest)(nil),        // 4: ember.v1.DelRequest
	(*DelResponse)(nil),       // 5: ember.v1.DelResponse
	(*ExistsRequest)(nil),     // 6: ember.v1.ExistsRequest
	(*ExistsResponse)(nil),    // 7: ember.v1.ExistsResponse
	(*TypeRequest)(nil),       // 8: ember.v1.TypeRequest
	(*TypeResponse)(nil),      // 9: ember.v1.TypeResponse
	(*ExpireRequest)(nil),     // 10: ember.v1.ExpireRequest
	(*ExpireResponse)(nil),    // 11: ember.v1.ExpireResponse
	(*TtlRequest)(nil),        // 12: ember.v1.TtlRequest
	(*TtlResponse)(nil),       // 13: ember.v1.TtlResponse
	(*HSetRequest)(nil),       // 14: ember.v1.HSetRequest
	(*HSetResponse)(nil),      // 15: ember.v1.HSetResponse
	(*HGetRequest)(nil),       // 16: ember.v1.HGetRequest
	(*HGetResponse)(nil),      // 17: ember.v1.HGetResponse
	(*HDelRequest)(nil),       // 18: ember.v1.HDelRequest
	(*HDelResponse)(nil),      // 19: ember.v1.HDelResponse
	(*HGetAllRequest)(nil),    // 20: ember.v1.HGetAllRequest
	(*HGetAllResponse)(nil),   // 21: ember.v1.HGetAllResponse
	(*LPushRequest)(nil),      // 22: ember.v1.LPushRequest
	(*LPushResponse)(nil),     // 23: ember.v1.LPushResponse
	(*RPushRequest)(nil),      // 24: ember.v1.RPushRequest
	(*RPushResponse)(nil),     // 25: ember.v1.RPushResponse
	(*LPopRequest)(nil),       // 26: ember.v1.LPopRequest
	(*LPopResponse)(nil),      // 27: ember.v1.LPopResponse
	(*RPopRequest)(nil),       // 28: ember.v1.RPopRequest
	(*RPopResponse)(nil),      // 29: ember.v1.RPopResponse
	(*LRangeRequest)(nil),     // 30: ember.v1.LRangeRequest
	(*LRangeResponse)(nil),    // 31: ember.v1.LRangeResponse
	(*SAddRequest)(nil),       // 32: ember.v1.SAddRequest
	(*SAddResponse)(nil),      // 33: ember.v1.SAddResponse
	(*SRemRequest)(nil),       // 34: ember.v1.SRemRequest
	(*SRemResponse)(nil),      // 35: ember.v1.SRemResponse
	(*SMembersRequest)(nil),   // 36: ember.v1.SMembersRequest
	(*SMembersResponse)(nil),  // 37: ember.v1.SMembersResponse
	(*SIsMemberRequest)(nil),  // 38: ember.v1.SIsMemberRequest
	(*SIsMemberResponse)(nil), // 39: ember.v1.SIsMemberResponse
	(*PublishRequest)(nil),    // 40: ember.v1.PublishRequest
	(*PublishResponse)(nil),   // 41: ember.v1.PublishResponse
	(*SubscribeRequest)(nil),  // 42: ember.v1.SubscribeRequest
	(*SubscribeMessage)(nil),  // 43: ember.v1.SubscribeMessage
	(*StatsRequest)(nil),      // 44: ember.v1.StatsRequest
	(*StatsResponse)(nil),     // 45: ember.v1.StatsResponse
	(*HealthRequest)(nil),     // 46: ember.v1.HealthRequest
	(*HealthResponse)(nil),    // 47: ember.v1.HealthResponse
	nil,                       // 48: ember.v1.HSetRequest.FieldsEntry
	nil,                       // 49: ember.v1.HGetAllResponse.FieldsEntry
}
var file_proto_ember_v1_cache_proto_depIdxs = []int32{
	48, // 0: ember.v1.HSetRequest.fields:type_name -> ember.v1.HSetRequest.FieldsEntry
	49, // 1: ember.v1.HGetAllResponse.fields:type_name -> ember.v1.HGetAllResponse.FieldsEntry
	0,  // 2: ember.v1.CacheService.Get:input_type -> ember.v1.GetRequest
	2,  // 3: ember.v1.CacheService.Set:input_type -> ember.v1.SetRequest
	4,  // 4: ember.v1.CacheService.Del:input_type -> ember.v1.DelRequest
	6,  // 5: ember.v1.CacheService.Exists:input_type -> ember.v1.ExistsRequest
	8,  // 6: ember.v1.CacheService.Type:input_type -> ember.v1.TypeRequest
	10, // 7: ember.v1.CacheService.Expire:input_type -> ember.v1.ExpireRequest
	12, // 8: ember.v1.CacheService.Ttl:input_type -> ember.v1.TtlRequest
	14, // 9: ember.v1.CacheService.HSet:input_type -> ember.v1.HSetRequest
	16, // 10: ember.v1.CacheService.HGet:input_type -> ember.v1.HGetRequest
	18, // 11: ember.v1.CacheService.HDel:input_type -> ember.v1.HDelRequest
	20, // 12: ember.v1.CacheService.HGetAll:input_type -> ember.v1.HGetAllRequest
	22, // 13: ember.v1.CacheService.LPush:input_type -> ember.v1.LPushRequest
	24, // 14: ember.v1.CacheService.RPush:input_type -> ember.v1.RPushRequest
	26, // 15: ember.v1.CacheService.LPop:input_type -> ember.v1.LPopRequest
	28, // 16: ember.v1.CacheService.RPop:input_type -> ember.v1.RPopRequest
	30, // 17: ember.v1.CacheService.LRange:input_type -> ember.v1.LRangeRequest
	32, // 18: ember.v1.CacheService.SAdd:input_type -> ember.v1.SAddRequest
	34, // 19: ember.v1.CacheService.SRem:input_type -> ember.v1.SRemRequest
	36, // 20: ember.v1.CacheService.SMembers:input_type -> ember.v1.SMembersRequest
	38, // 21: ember.v1.CacheService.SIsMember:input_type -> ember.v1.SIsMemberRequest
	40, // 22: ember.v1.CacheService.Publish:input_type -> ember.v1.PublishRequest
	42, // 23: ember.v1.CacheService.Subscribe:input_type -> ember.v1.SubscribeRequest
	44, // 24: ember.v1.CacheService.Stats:input_type -> ember.v1.StatsRequest
	46, // 25: ember.v1.CacheService.Health:input_type -> ember.v1.HealthRequest
	1,  // 26: ember.v1.CacheService.Get:output_type -> ember.v1.GetResponse
	3,  // 27: ember.v1.CacheService.Set:output_type -> ember.v1.SetResponse
	5,  // 28: ember.v1.CacheService.Del:output_type -> ember.v1.DelResponse
	7,  // 29: ember.v1.CacheService.Exists:output_type -> ember.v1.ExistsResponse
	9,  // 30: ember.v1.CacheService.Type:output_type -> ember.v1.TypeResponse
	11, // 31: ember.v1.CacheService.Expire:output_type -> ember.v1.ExpireResponse
	13, // 32: ember.v1.CacheService.Ttl:output_type -> ember.v1.TtlResponse
	15, // 33: ember.v1.CacheService.HSet:output_type -> ember.v1.HSetResponse
	17, // 34: ember.v1.CacheService.HGet:output_type -> ember.v1.HGetResponse
	19, // 35: ember.v1.CacheService.HDel:output_type -> ember.v1.HDelResponse
	21, // 36: ember.v1.CacheService.HGetAll:output_type -> ember.v1.HGetAllResponse
	23, // 37: ember.v1.CacheService.LPush:output_type -> ember.v1.LPushResponse
	25, // 38: ember.v1.CacheService.RPush:output_type -> ember.v1.RPushResponse
	27, // 39: ember.v1.CacheService.LPop:output_type -> ember.v1.LPopResponse
	29, // 40: ember.v1.CacheService.RPop:output_type -> ember.v1.RPopResponse
	31, // 41: ember.v1.CacheService.LRange:output_type -> ember.v1.LRangeResponse
	33, // 42: ember.v1.CacheService.SAdd:output_type -> ember.v1.SAddResponse
	35, // 43: ember.v1.CacheService.SRem:output_type -> ember.v1.SRemResponse
	37, // 44: ember.v1.CacheService.SMembers:output_type -> ember.v1.SMembersResponse
	39, // 45: ember.v1.CacheService.SIsMember:output_type -> ember.v1.SIsMemberResponse
	41, // 46: ember.v1.CacheService.Publish:output_type -> ember.v1.PublishResponse
	43, // 47: ember.v1.CacheService.Subscribe:output_type -> ember.v1.SubscribeMessage
	45, // 48: ember.v1.CacheService.Stats:output_type -> ember.v1.StatsResponse
	47, // 49: ember.v1.CacheService.Health:output_type -> ember.v1.HealthResponse
	26, // [26:50] is the sub-list for method output_type
	2,  // [2:26] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ember_v1_cache_proto_init() }
func file_proto_ember_v1_cache_proto_init() {
	if File_proto_ember_v1_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ember_v1_cache_proto_rawDesc), len(file_proto_ember_v1_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   50,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ember_v1_cache_proto_goTypes,
		DependencyIndexes: file_proto_ember_v1_cache_proto_depIdxs,
		MessageInfos:      file_proto_ember_v1_cache_proto_msgTypes,
	}.Build()
	File_proto_ember_v1_cache_proto = out.File
	file_proto_ember_v1_cache_proto_goTypes = nil
	file_proto_ember_v1_cache_proto_depIdxs = nil
}
