// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.3
// source: proto/ember/v1/semantic_cache.proto

package emberv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Prompt              string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,2,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GetRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hit           bool                   `protobuf:"varint,1,opt,name=hit,proto3" json:"hit,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Similarity    float32                `protobuf:"fixed32,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
	ExactMatch    bool                   `protobuf:"varint,4,opt,name=exact_match,json=exactMatch,proto3" json:"exact_match,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetHit() bool {
	if x != nil {
		return x.Hit
	}
	return false
}

func (x *GetResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *GetResponse) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *GetResponse) GetExactMatch() bool {
	if x != nil {
		return x.ExactMatch
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *SetRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *SetRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{6}
}

type StatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalEntries  int64                  `protobuf:"varint,1,opt,name=total_entries,json=totalEntries,proto3" json:"total_entries,omitempty"`
	CacheHits     int64                  `protobuf:"varint,2,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses   int64                  `protobuf:"varint,3,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	TotalQueries  int64                  `protobuf:"varint,4,opt,name=total_queries,json=totalQueries,proto3" json:"total_queries,omitempty"`
	HitRate       float64                `protobuf:"fixed64,5,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetTotalEntries() int64 {
	if x != nil {
		return x.TotalEntries
	}
	return 0
}

func (x *StatsResponse) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *StatsResponse) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *StatsResponse) GetTotalQueries() int64 {
	if x != nil {
		return x.TotalQueries
	}
	return 0
}

func (x *StatsResponse) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ember_v1_semantic_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_ember_v1_semantic_cache_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_ember_v1_semantic_cache_proto protoreflect.FileDescriptor

const file_proto_ember_v1_semantic_cache_proto_rawDesc = "" +
	"\n" +
	"#proto/ember/v1/semantic_cache.proto\x12\bember.v1\"W\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x121\n" +
	"\x14similarity_threshold\x18\x02 \x01(\x02R\x13similarityThreshold\"|\n" +
	"\vGetResponse\x12\x10\n" +
	"\x03hit\x18\x01 \x01(\bR\x03hit\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1e\n" +
	"\n" +
	"similarity\x18\x03 \x01(\x02R\n" +
	"similarity\x12\x1f\n" +
	"\vexact_match\x18\x04 \x01(\bR\n" +
	"exactMatch\"a\n" +
	"\n" +
	"SetRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1a\n" +
	"\bresponse\x18\x02 \x01(\tR\bresponse\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\"\x1d\n" +
	"\vSetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"'\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"\x0e\n" +
	"\fStatsRequest\"\xb6\x01\n" +
	"\rStatsResponse\x12#\n" +
	"\rtotal_entries\x18\x01 \x01(\x03R\ftotalEntries\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x02 \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x03 \x01(\x03R\vcacheMisses\x12#\n" +
	"\rtotal_queries\x18\x04 \x01(\x03R\ftotalQueries\x12\x19\n" +
	"\bhit_rate\x18\x05 \x01(\x01R\ahitRate\"\x0f\n" +
	"\rHealthRequest\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xb2\x02\n" +
	"\x14SemanticCacheService\x122\n" +
	"\x03Get\x12\x14.ember.v1.GetRequest\x1a\x15.ember.v1.GetResponse\x122\n" +
	"\x03Set\x12\x14.ember.v1.SetRequest\x1a\x15.ember.v1.SetResponse\x12;\n" +
	"\x06Delete\x12\x17.ember.v1.DeleteRequest\x1a\x18.ember.v1.DeleteResponse\x128\n" +
	"\x05Stats\x12\x16.ember.v1.StatsRequest\x1a\x17.ember.v1.StatsResponse\x12;\n" +
	"\x06Health\x12\x17.ember.v1.HealthRequest\x1a\x18.ember.v1.HealthResponseB>Z<github.com/EricNguyen1206/erion-ember/proto/ember/v1;emberv1b\x06proto3"

var (
	file_proto_ember_v1_semantic_cache_proto_rawDescOnce sync.Once
	file_proto_ember_v1_semantic_cache_proto_rawDescData []byte
)

func file_proto_ember_v1_semantic_cache_proto_rawDescGZIP() []byte {
	file_proto_ember_v1_semantic_cache_proto_rawDescOnce.Do(func() {
		file_proto_ember_v1_semantic_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ember_v1_semantic_cache_proto_rawDesc), len(file_proto_ember_v1_semantic_cache_proto_rawDesc)))
	})
	return file_proto_ember_v1_semantic_cache_proto_rawDescData
}

var file_proto_ember_v1_semantic_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ember_v1_semantic_cache_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: ember.v1.GetRequest
	(*GetResponse)(nil),    // 1: ember.v1.GetResponse
	(*SetRequest)(nil),     // 2: ember.v1.SetRequest
	(*SetResponse)(nil),    // 3: ember.v1.SetResponse
	(*DeleteRequest)(nil),  // 4: ember.v1.DeleteRequest
	(*DeleteResponse)(nil), // 5: ember.v1.DeleteResponse
	(*StatsRequest)(nil),   // 6: ember.v1.StatsRequest
	(*StatsResponse)(nil),  // 7: ember.v1.StatsResponse
	(*HealthRequest)(nil),  // 8: ember.v1.HealthRequest
	(*HealthResponse)(nil), // 9: ember.v1.HealthResponse
}
var file_proto_ember_v1_semantic_cache_proto_depIdxs = []int32{
	0, // 0: ember.v1.SemanticCacheService.Get:input_type -> ember.v1.GetRequest
	2, // 1: ember.v1.SemanticCacheService.Set:input_type -> ember.v1.SetRequest
	4, // 2: ember.v1.SemanticCacheService.Delete:input_type -> ember.v1.DeleteRequest
	6, // 3: ember.v1.SemanticCacheService.Stats:input_type -> ember.v1.StatsRequest
	8, // 4: ember.v1.SemanticCacheService.Health:input_type -> ember.v1.HealthRequest
	1, // 5: ember.v1.SemanticCacheService.Get:output_type -> ember.v1.GetResponse
	3, // 6: ember.v1.SemanticCacheService.Set:output_type -> ember.v1.SetResponse
	5, // 7: ember.v1.SemanticCacheService.Delete:output_type -> ember.v1.DeleteResponse
	7, // 8: ember.v1.SemanticCacheService.Stats:output_type -> ember.v1.StatsResponse
	9, // 9: ember.v1.SemanticCacheService.Health:output_type -> ember.v1.HealthResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ember_v1_semantic_cache_proto_init() }
func file_proto_ember_v1_semantic_cache_proto_init() {
	if File_proto_ember_v1_semantic_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ember_v1_semantic_cache_proto_rawDesc), len(file_proto_ember_v1_semantic_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ember_v1_semantic_cache_proto_goTypes,
		DependencyIndexes: file_proto_ember_v1_semantic_cache_proto_depIdxs,
		MessageInfos:      file_proto_ember_v1_semantic_cache_proto_msgTypes,
	}.Build()
	File_proto_ember_v1_semantic_cache_proto = out.File
	file_proto_ember_v1_semantic_cache_proto_goTypes = nil
	file_proto_ember_v1_semantic_cache_proto_depIdxs = nil
}
